# Generated by Django 5.1.7 on 2025-03-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstitutionArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=20, unique=True)),
                ('chapter', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('tags', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CaseLaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('tags', models.CharField(max_length=255)),
                ('related_articles', models.ManyToManyField(to='core.constitutionarticle')),
            ],
        ),
    ]
