# Generated by Django 5.1.7 on 2025-03-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_constitutionarticle_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='constitutionarticle',
            name='implication',
            field=models.TextField(default='the principle supports the client', help_text='What this article establishes or implies.'),
        ),
        migrations.AddField(
            model_name='constitutionarticle',
            name='potential_counterargument',
            field=models.TextField(default='an alternative interpretation limits this right', help_text='Possible opposing view or limitation.'),
        ),
    ]
