# Generated by Django 5.1.7 on 2025-04-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_constitutionarticle_implication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselaw',
            name='authority_level',
            field=models.IntegerField(default=1),
        ),
    ]
