# Generated by Django 5.1.7 on 2025-05-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_caselaw_authority_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselaw',
            name='court_name',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
